# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EQ_INFO_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1227, 640)
        Form.setMaximumSize(QtCore.QSize(16777215, 640))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_equipment_01 = QtWidgets.QFrame(Form)
        self.frame_equipment_01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_equipment_01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_equipment_01.setObjectName("frame_equipment_01")
        self.verticalLayout_equipment_01 = QtWidgets.QVBoxLayout(self.frame_equipment_01)
        self.verticalLayout_equipment_01.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_equipment_01.setSpacing(3)
        self.verticalLayout_equipment_01.setObjectName("verticalLayout_equipment_01")
        self.splitter_4 = QtWidgets.QSplitter(self.frame_equipment_01)
        self.splitter_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.groupBox_eq_info = QtWidgets.QGroupBox(self.splitter_4)
        self.groupBox_eq_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_eq_info.setObjectName("groupBox_eq_info")
        self.verticalLayout_eq_info = QtWidgets.QVBoxLayout(self.groupBox_eq_info)
        self.verticalLayout_eq_info.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_eq_info.setSpacing(3)
        self.verticalLayout_eq_info.setObjectName("verticalLayout_eq_info")
        self.widget_eq_info_01 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_01.setObjectName("widget_eq_info_01")
        self.horizontalLayout_eq_info_01 = QtWidgets.QHBoxLayout(self.widget_eq_info_01)
        self.horizontalLayout_eq_info_01.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_01.setSpacing(2)
        self.horizontalLayout_eq_info_01.setObjectName("horizontalLayout_eq_info_01")
        self.label_eq_info_01_equipment_name = QtWidgets.QLabel(self.widget_eq_info_01)
        self.label_eq_info_01_equipment_name.setMinimumSize(QtCore.QSize(100, 0))
        self.label_eq_info_01_equipment_name.setObjectName("label_eq_info_01_equipment_name")
        self.horizontalLayout_eq_info_01.addWidget(self.label_eq_info_01_equipment_name)
        self.lineEdit_eq_info_01_equipment_name = QtWidgets.QLineEdit(self.widget_eq_info_01)
        self.lineEdit_eq_info_01_equipment_name.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_eq_info_01_equipment_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_01_equipment_name.setObjectName("lineEdit_eq_info_01_equipment_name")
        self.horizontalLayout_eq_info_01.addWidget(self.lineEdit_eq_info_01_equipment_name)
        self.horizontalLayout_eq_info_01.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_01)
        self.widget_eq_info_3 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_3.setObjectName("widget_eq_info_3")
        self.horizontalLayout_eq_info_3 = QtWidgets.QHBoxLayout(self.widget_eq_info_3)
        self.horizontalLayout_eq_info_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_3.setSpacing(2)
        self.horizontalLayout_eq_info_3.setObjectName("horizontalLayout_eq_info_3")
        self.label_eq_type = QtWidgets.QLabel(self.widget_eq_info_3)
        self.label_eq_type.setMinimumSize(QtCore.QSize(100, 0))
        self.label_eq_type.setObjectName("label_eq_type")
        self.horizontalLayout_eq_info_3.addWidget(self.label_eq_type)
        self.comboBox_eq_info_type = QtWidgets.QComboBox(self.widget_eq_info_3)
        self.comboBox_eq_info_type.setObjectName("comboBox_eq_info_type")
        self.horizontalLayout_eq_info_3.addWidget(self.comboBox_eq_info_type)
        self.horizontalLayout_eq_info_3.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_3)
        self.widget_eq_info_02 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_02.setObjectName("widget_eq_info_02")
        self.horizontalLayout_eq_info_02 = QtWidgets.QHBoxLayout(self.widget_eq_info_02)
        self.horizontalLayout_eq_info_02.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_02.setSpacing(2)
        self.horizontalLayout_eq_info_02.setObjectName("horizontalLayout_eq_info_02")
        self.label_eq_info_02_equipment_type = QtWidgets.QLabel(self.widget_eq_info_02)
        self.label_eq_info_02_equipment_type.setMinimumSize(QtCore.QSize(100, 0))
        self.label_eq_info_02_equipment_type.setObjectName("label_eq_info_02_equipment_type")
        self.horizontalLayout_eq_info_02.addWidget(self.label_eq_info_02_equipment_type)
        self.lineEdit_eq_info_02_equipment_mark = QtWidgets.QLineEdit(self.widget_eq_info_02)
        self.lineEdit_eq_info_02_equipment_mark.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_eq_info_02_equipment_mark.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_02_equipment_mark.setObjectName("lineEdit_eq_info_02_equipment_mark")
        self.horizontalLayout_eq_info_02.addWidget(self.lineEdit_eq_info_02_equipment_mark)
        self.horizontalLayout_eq_info_02.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_02)
        self.widget_eq_info_03 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_03.setObjectName("widget_eq_info_03")
        self.horizontalLayout_eq_info_03 = QtWidgets.QHBoxLayout(self.widget_eq_info_03)
        self.horizontalLayout_eq_info_03.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_03.setSpacing(2)
        self.horizontalLayout_eq_info_03.setObjectName("horizontalLayout_eq_info_03")
        self.label_eq_info_03_equipment_factory_num = QtWidgets.QLabel(self.widget_eq_info_03)
        self.label_eq_info_03_equipment_factory_num.setMinimumSize(QtCore.QSize(100, 0))
        self.label_eq_info_03_equipment_factory_num.setObjectName("label_eq_info_03_equipment_factory_num")
        self.horizontalLayout_eq_info_03.addWidget(self.label_eq_info_03_equipment_factory_num)
        self.lineEdit_eq_info_03_equipment_factory_num = QtWidgets.QLineEdit(self.widget_eq_info_03)
        self.lineEdit_eq_info_03_equipment_factory_num.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_eq_info_03_equipment_factory_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_03_equipment_factory_num.setObjectName("lineEdit_eq_info_03_equipment_factory_num")
        self.horizontalLayout_eq_info_03.addWidget(self.lineEdit_eq_info_03_equipment_factory_num)
        self.horizontalLayout_eq_info_03.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_03)
        self.widget_eq_info_04 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_04.setObjectName("widget_eq_info_04")
        self.horizontalLayout_eq_info_04 = QtWidgets.QHBoxLayout(self.widget_eq_info_04)
        self.horizontalLayout_eq_info_04.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_04.setSpacing(2)
        self.horizontalLayout_eq_info_04.setObjectName("horizontalLayout_eq_info_04")
        self.label_eq_info_04_manufacturer_name = QtWidgets.QLabel(self.widget_eq_info_04)
        self.label_eq_info_04_manufacturer_name.setMinimumSize(QtCore.QSize(100, 0))
        self.label_eq_info_04_manufacturer_name.setObjectName("label_eq_info_04_manufacturer_name")
        self.horizontalLayout_eq_info_04.addWidget(self.label_eq_info_04_manufacturer_name)
        self.lineEdit_eq_info_04_equipment_manufacturer = QtWidgets.QLineEdit(self.widget_eq_info_04)
        self.lineEdit_eq_info_04_equipment_manufacturer.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_eq_info_04_equipment_manufacturer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_04_equipment_manufacturer.setObjectName("lineEdit_eq_info_04_equipment_manufacturer")
        self.horizontalLayout_eq_info_04.addWidget(self.lineEdit_eq_info_04_equipment_manufacturer)
        self.horizontalLayout_eq_info_04.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_04)
        self.widget_eq_info_05 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_05.setObjectName("widget_eq_info_05")
        self.horizontalLayout_eq_info_5 = QtWidgets.QHBoxLayout(self.widget_eq_info_05)
        self.horizontalLayout_eq_info_5.setContentsMargins(2, 1, 1, 1)
        self.horizontalLayout_eq_info_5.setSpacing(2)
        self.horizontalLayout_eq_info_5.setObjectName("horizontalLayout_eq_info_5")
        self.label_eq_info_05_eq_manufacturing_date = QtWidgets.QLabel(self.widget_eq_info_05)
        self.label_eq_info_05_eq_manufacturing_date.setMinimumSize(QtCore.QSize(130, 0))
        self.label_eq_info_05_eq_manufacturing_date.setObjectName("label_eq_info_05_eq_manufacturing_date")
        self.horizontalLayout_eq_info_5.addWidget(self.label_eq_info_05_eq_manufacturing_date)
        self.dateEdit_eq_info_05_eq_manufacturing_date = QtWidgets.QDateEdit(self.widget_eq_info_05)
        self.dateEdit_eq_info_05_eq_manufacturing_date.setMaximumSize(QtCore.QSize(110, 16777215))
        self.dateEdit_eq_info_05_eq_manufacturing_date.setObjectName("dateEdit_eq_info_05_eq_manufacturing_date")
        self.horizontalLayout_eq_info_5.addWidget(self.dateEdit_eq_info_05_eq_manufacturing_date)
        self.line_eq_info_05_razdelitel_01 = QtWidgets.QFrame(self.widget_eq_info_05)
        self.line_eq_info_05_razdelitel_01.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_eq_info_05_razdelitel_01.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_eq_info_05_razdelitel_01.setObjectName("line_eq_info_05_razdelitel_01")
        self.horizontalLayout_eq_info_5.addWidget(self.line_eq_info_05_razdelitel_01)
        self.label_eq_info_05_eq_commissioning_date = QtWidgets.QLabel(self.widget_eq_info_05)
        self.label_eq_info_05_eq_commissioning_date.setMinimumSize(QtCore.QSize(105, 0))
        self.label_eq_info_05_eq_commissioning_date.setObjectName("label_eq_info_05_eq_commissioning_date")
        self.horizontalLayout_eq_info_5.addWidget(self.label_eq_info_05_eq_commissioning_date)
        self.dateEdit_eq_info_05_eq_commissioning_date = QtWidgets.QDateEdit(self.widget_eq_info_05)
        self.dateEdit_eq_info_05_eq_commissioning_date.setMaximumSize(QtCore.QSize(110, 16777215))
        self.dateEdit_eq_info_05_eq_commissioning_date.setObjectName("dateEdit_eq_info_05_eq_commissioning_date")
        self.horizontalLayout_eq_info_5.addWidget(self.dateEdit_eq_info_05_eq_commissioning_date)
        self.line_eq_info_05_razdelitel_02 = QtWidgets.QFrame(self.widget_eq_info_05)
        self.line_eq_info_05_razdelitel_02.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_eq_info_05_razdelitel_02.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_eq_info_05_razdelitel_02.setObjectName("line_eq_info_05_razdelitel_02")
        self.horizontalLayout_eq_info_5.addWidget(self.line_eq_info_05_razdelitel_02)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_eq_info_5.addItem(spacerItem)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_05)
        self.widget_eq_info_06 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_06.setObjectName("widget_eq_info_06")
        self.horizontalLayout_eq_info_6 = QtWidgets.QHBoxLayout(self.widget_eq_info_06)
        self.horizontalLayout_eq_info_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_6.setSpacing(2)
        self.horizontalLayout_eq_info_6.setObjectName("horizontalLayout_eq_info_6")
        self.label_eq_info_06_equipment_inv_num = QtWidgets.QLabel(self.widget_eq_info_06)
        self.label_eq_info_06_equipment_inv_num.setMinimumSize(QtCore.QSize(130, 0))
        self.label_eq_info_06_equipment_inv_num.setObjectName("label_eq_info_06_equipment_inv_num")
        self.horizontalLayout_eq_info_6.addWidget(self.label_eq_info_06_equipment_inv_num)
        self.lineEdit_eq_info_06_equipment_inv_num = QtWidgets.QLineEdit(self.widget_eq_info_06)
        self.lineEdit_eq_info_06_equipment_inv_num.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_eq_info_06_equipment_inv_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_06_equipment_inv_num.setObjectName("lineEdit_eq_info_06_equipment_inv_num")
        self.horizontalLayout_eq_info_6.addWidget(self.lineEdit_eq_info_06_equipment_inv_num)
        self.horizontalLayout_eq_info_6.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_06)
        self.widget_eq_info_07 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_07.setObjectName("widget_eq_info_07")
        self.horizontalLayout_eq_info_7 = QtWidgets.QHBoxLayout(self.widget_eq_info_07)
        self.horizontalLayout_eq_info_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_7.setSpacing(2)
        self.horizontalLayout_eq_info_7.setObjectName("horizontalLayout_eq_info_7")
        self.label_eq_info_07_measuring_range = QtWidgets.QLabel(self.widget_eq_info_07)
        self.label_eq_info_07_measuring_range.setMinimumSize(QtCore.QSize(130, 0))
        self.label_eq_info_07_measuring_range.setObjectName("label_eq_info_07_measuring_range")
        self.horizontalLayout_eq_info_7.addWidget(self.label_eq_info_07_measuring_range)
        self.lineEdit_eq_info_07_eq_measuring_range_from = QtWidgets.QLineEdit(self.widget_eq_info_07)
        self.lineEdit_eq_info_07_eq_measuring_range_from.setObjectName("lineEdit_eq_info_07_eq_measuring_range_from")
        self.horizontalLayout_eq_info_7.addWidget(self.lineEdit_eq_info_07_eq_measuring_range_from)
        self.label_eq_info_07_razdelitel = QtWidgets.QLabel(self.widget_eq_info_07)
        self.label_eq_info_07_razdelitel.setObjectName("label_eq_info_07_razdelitel")
        self.horizontalLayout_eq_info_7.addWidget(self.label_eq_info_07_razdelitel)
        self.lineEdit_eq_info_07_eq_measuring_range_to = QtWidgets.QLineEdit(self.widget_eq_info_07)
        self.lineEdit_eq_info_07_eq_measuring_range_to.setObjectName("lineEdit_eq_info_07_eq_measuring_range_to")
        self.horizontalLayout_eq_info_7.addWidget(self.lineEdit_eq_info_07_eq_measuring_range_to)
        self.label_eq_units_of_measurement = QtWidgets.QLabel(self.widget_eq_info_07)
        self.label_eq_units_of_measurement.setObjectName("label_eq_units_of_measurement")
        self.horizontalLayout_eq_info_7.addWidget(self.label_eq_units_of_measurement)
        self.lineEdit_eq_units_of_measurement = QtWidgets.QLineEdit(self.widget_eq_info_07)
        self.lineEdit_eq_units_of_measurement.setObjectName("lineEdit_eq_units_of_measurement")
        self.horizontalLayout_eq_info_7.addWidget(self.lineEdit_eq_units_of_measurement)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_eq_info_7.addItem(spacerItem1)
        self.horizontalLayout_eq_info_7.setStretch(6, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_07)
        self.widget_eq_info_08 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_08.setObjectName("widget_eq_info_08")
        self.horizontalLayout_eq_info_8 = QtWidgets.QHBoxLayout(self.widget_eq_info_08)
        self.horizontalLayout_eq_info_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_8.setSpacing(2)
        self.horizontalLayout_eq_info_8.setObjectName("horizontalLayout_eq_info_8")
        self.label_eq_info_08_eq_accuracy_class = QtWidgets.QLabel(self.widget_eq_info_08)
        self.label_eq_info_08_eq_accuracy_class.setMinimumSize(QtCore.QSize(130, 0))
        self.label_eq_info_08_eq_accuracy_class.setObjectName("label_eq_info_08_eq_accuracy_class")
        self.horizontalLayout_eq_info_8.addWidget(self.label_eq_info_08_eq_accuracy_class)
        self.lineEdit_eq_info_08_eq_accuracy_class = QtWidgets.QLineEdit(self.widget_eq_info_08)
        self.lineEdit_eq_info_08_eq_accuracy_class.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_08_eq_accuracy_class.setObjectName("lineEdit_eq_info_08_eq_accuracy_class")
        self.horizontalLayout_eq_info_8.addWidget(self.lineEdit_eq_info_08_eq_accuracy_class)
        self.horizontalLayout_eq_info_8.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_08)
        self.widget_eq_info_09 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_09.setObjectName("widget_eq_info_09")
        self.horizontalLayout_eq_info_9 = QtWidgets.QHBoxLayout(self.widget_eq_info_09)
        self.horizontalLayout_eq_info_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_9.setSpacing(2)
        self.horizontalLayout_eq_info_9.setObjectName("horizontalLayout_eq_info_9")
        self.label_eq_info_09_technical_character = QtWidgets.QLabel(self.widget_eq_info_09)
        self.label_eq_info_09_technical_character.setMinimumSize(QtCore.QSize(130, 0))
        self.label_eq_info_09_technical_character.setObjectName("label_eq_info_09_technical_character")
        self.horizontalLayout_eq_info_9.addWidget(self.label_eq_info_09_technical_character)
        self.lineEdit_eq_info_09_eq_technical_character = QtWidgets.QLineEdit(self.widget_eq_info_09)
        self.lineEdit_eq_info_09_eq_technical_character.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_09_eq_technical_character.setObjectName("lineEdit_eq_info_09_eq_technical_character")
        self.horizontalLayout_eq_info_9.addWidget(self.lineEdit_eq_info_09_eq_technical_character)
        self.horizontalLayout_eq_info_9.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_09)
        self.widget_eq_info_10 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_10.setObjectName("widget_eq_info_10")
        self.horizontalLayout_eq_info_10 = QtWidgets.QHBoxLayout(self.widget_eq_info_10)
        self.horizontalLayout_eq_info_10.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_10.setSpacing(2)
        self.horizontalLayout_eq_info_10.setObjectName("horizontalLayout_eq_info_10")
        self.label_eq_info_10_other_info = QtWidgets.QLabel(self.widget_eq_info_10)
        self.label_eq_info_10_other_info.setMinimumSize(QtCore.QSize(130, 0))
        self.label_eq_info_10_other_info.setObjectName("label_eq_info_10_other_info")
        self.horizontalLayout_eq_info_10.addWidget(self.label_eq_info_10_other_info)
        self.lineEdit_eq_info_10_eq_other_info = QtWidgets.QLineEdit(self.widget_eq_info_10)
        self.lineEdit_eq_info_10_eq_other_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_eq_info_10_eq_other_info.setObjectName("lineEdit_eq_info_10_eq_other_info")
        self.horizontalLayout_eq_info_10.addWidget(self.lineEdit_eq_info_10_eq_other_info)
        self.horizontalLayout_eq_info_10.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_10)
        self.widget_eq_info_11 = QtWidgets.QWidget(self.groupBox_eq_info)
        self.widget_eq_info_11.setObjectName("widget_eq_info_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_eq_info_11)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_eq_passport = QtWidgets.QLabel(self.widget_eq_info_11)
        self.label_eq_passport.setMinimumSize(QtCore.QSize(130, 0))
        self.label_eq_passport.setObjectName("label_eq_passport")
        self.horizontalLayout.addWidget(self.label_eq_passport)
        self.lineEdit_eq_passport_file = QtWidgets.QLineEdit(self.widget_eq_info_11)
        self.lineEdit_eq_passport_file.setObjectName("lineEdit_eq_passport_file")
        self.horizontalLayout.addWidget(self.lineEdit_eq_passport_file)
        self.pushButton_eq_passport_add = QtWidgets.QPushButton(self.widget_eq_info_11)
        self.pushButton_eq_passport_add.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_eq_passport_add.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_eq_passport_add.setText("")
        self.pushButton_eq_passport_add.setObjectName("pushButton_eq_passport_add")
        self.horizontalLayout.addWidget(self.pushButton_eq_passport_add)
        self.pushButton_eq_passport_upload = QtWidgets.QPushButton(self.widget_eq_info_11)
        self.pushButton_eq_passport_upload.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_eq_passport_upload.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_eq_passport_upload.setText("")
        self.pushButton_eq_passport_upload.setObjectName("pushButton_eq_passport_upload")
        self.horizontalLayout.addWidget(self.pushButton_eq_passport_upload)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_eq_info.addWidget(self.widget_eq_info_11)
        self.groupBox_eq_test_method = QtWidgets.QGroupBox(self.splitter_4)
        self.groupBox_eq_test_method.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_eq_test_method.setObjectName("groupBox_eq_test_method")
        self.verticalLayout_eq_test_method = QtWidgets.QVBoxLayout(self.groupBox_eq_test_method)
        self.verticalLayout_eq_test_method.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_eq_test_method.setSpacing(2)
        self.verticalLayout_eq_test_method.setObjectName("verticalLayout_eq_test_method")
        self.treeWidget_eq_test_method = QtWidgets.QTreeWidget(self.groupBox_eq_test_method)
        self.treeWidget_eq_test_method.setObjectName("treeWidget_eq_test_method")
        self.treeWidget_eq_test_method.headerItem().setText(0, "1")
        self.verticalLayout_eq_test_method.addWidget(self.treeWidget_eq_test_method)
        self.verticalLayout_eq_test_method.setStretch(0, 1)
        self.verticalLayout_equipment_01.addWidget(self.splitter_4)
        self.tabWidget_eq_info = QtWidgets.QTabWidget(self.frame_equipment_01)
        self.tabWidget_eq_info.setObjectName("tabWidget_eq_info")
        self.tab_verification_info = QtWidgets.QWidget()
        self.tab_verification_info.setObjectName("tab_verification_info")
        self.verticalLayout_tab_verification_info = QtWidgets.QVBoxLayout(self.tab_verification_info)
        self.verticalLayout_tab_verification_info.setContentsMargins(1, 2, 2, 2)
        self.verticalLayout_tab_verification_info.setSpacing(2)
        self.verticalLayout_tab_verification_info.setObjectName("verticalLayout_tab_verification_info")
        self.widget_eq_verification_info_01 = QtWidgets.QWidget(self.tab_verification_info)
        self.widget_eq_verification_info_01.setObjectName("widget_eq_verification_info_01")
        self.horizontalLayout_eq_verification_info_01 = QtWidgets.QHBoxLayout(self.widget_eq_verification_info_01)
        self.horizontalLayout_eq_verification_info_01.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_verification_info_01.setSpacing(3)
        self.horizontalLayout_eq_verification_info_01.setObjectName("horizontalLayout_eq_verification_info_01")
        self.frame_eq_verification_info_01_01 = QtWidgets.QFrame(self.widget_eq_verification_info_01)
        self.frame_eq_verification_info_01_01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_eq_verification_info_01_01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_eq_verification_info_01_01.setObjectName("frame_eq_verification_info_01_01")
        self.gridLayout_eq_verification_info_01_01 = QtWidgets.QGridLayout(self.frame_eq_verification_info_01_01)
        self.gridLayout_eq_verification_info_01_01.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_eq_verification_info_01_01.setSpacing(3)
        self.gridLayout_eq_verification_info_01_01.setObjectName("gridLayout_eq_verification_info_01_01")
        self.label_eq_verification_certificate = QtWidgets.QLabel(self.frame_eq_verification_info_01_01)
        self.label_eq_verification_certificate.setObjectName("label_eq_verification_certificate")
        self.gridLayout_eq_verification_info_01_01.addWidget(self.label_eq_verification_certificate, 2, 0, 1, 1)
        self.lineEdit_eq_verification_certificate = QtWidgets.QLineEdit(self.frame_eq_verification_info_01_01)
        self.lineEdit_eq_verification_certificate.setObjectName("lineEdit_eq_verification_certificate")
        self.gridLayout_eq_verification_info_01_01.addWidget(self.lineEdit_eq_verification_certificate, 2, 1, 1, 1)
        self.comboBox_eq_verification_result = QtWidgets.QComboBox(self.frame_eq_verification_info_01_01)
        self.comboBox_eq_verification_result.setObjectName("comboBox_eq_verification_result")
        self.comboBox_eq_verification_result.addItem("")
        self.comboBox_eq_verification_result.addItem("")
        self.gridLayout_eq_verification_info_01_01.addWidget(self.comboBox_eq_verification_result, 1, 1, 1, 1)
        self.lineEdit_eq_organization_verification = QtWidgets.QLineEdit(self.frame_eq_verification_info_01_01)
        self.lineEdit_eq_organization_verification.setObjectName("lineEdit_eq_organization_verification")
        self.gridLayout_eq_verification_info_01_01.addWidget(self.lineEdit_eq_organization_verification, 0, 1, 1, 1)
        self.label_eq_verification_result = QtWidgets.QLabel(self.frame_eq_verification_info_01_01)
        self.label_eq_verification_result.setObjectName("label_eq_verification_result")
        self.gridLayout_eq_verification_info_01_01.addWidget(self.label_eq_verification_result, 1, 0, 1, 1)
        self.label_eq_organization_verification = QtWidgets.QLabel(self.frame_eq_verification_info_01_01)
        self.label_eq_organization_verification.setObjectName("label_eq_organization_verification")
        self.gridLayout_eq_verification_info_01_01.addWidget(self.label_eq_organization_verification, 0, 0, 1, 1)
        self.horizontalLayout_eq_verification_info_01.addWidget(self.frame_eq_verification_info_01_01)
        self.frame_eq_verification_info_01_02 = QtWidgets.QFrame(self.widget_eq_verification_info_01)
        self.frame_eq_verification_info_01_02.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_eq_verification_info_01_02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_eq_verification_info_01_02.setObjectName("frame_eq_verification_info_01_02")
        self.formLayout_eq_verification_info_01_02 = QtWidgets.QFormLayout(self.frame_eq_verification_info_01_02)
        self.formLayout_eq_verification_info_01_02.setContentsMargins(2, 2, 2, 2)
        self.formLayout_eq_verification_info_01_02.setSpacing(3)
        self.formLayout_eq_verification_info_01_02.setObjectName("formLayout_eq_verification_info_01_02")
        self.label_eq_verification_date = QtWidgets.QLabel(self.frame_eq_verification_info_01_02)
        self.label_eq_verification_date.setObjectName("label_eq_verification_date")
        self.formLayout_eq_verification_info_01_02.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_eq_verification_date)
        self.dateEdit_eq_verification_date = QtWidgets.QDateEdit(self.frame_eq_verification_info_01_02)
        self.dateEdit_eq_verification_date.setMaximumSize(QtCore.QSize(110, 16777215))
        self.dateEdit_eq_verification_date.setObjectName("dateEdit_eq_verification_date")
        self.formLayout_eq_verification_info_01_02.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_eq_verification_date)
        self.label_eq_regular_verification_date = QtWidgets.QLabel(self.frame_eq_verification_info_01_02)
        self.label_eq_regular_verification_date.setObjectName("label_eq_regular_verification_date")
        self.formLayout_eq_verification_info_01_02.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_eq_regular_verification_date)
        self.dateEdit_eq_regular_verification_date = QtWidgets.QDateEdit(self.frame_eq_verification_info_01_02)
        self.dateEdit_eq_regular_verification_date.setMaximumSize(QtCore.QSize(110, 16777215))
        self.dateEdit_eq_regular_verification_date.setObjectName("dateEdit_eq_regular_verification_date")
        self.formLayout_eq_verification_info_01_02.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_eq_regular_verification_date)
        self.horizontalLayout_eq_verification_info_01.addWidget(self.frame_eq_verification_info_01_02)
        self.horizontalLayout_eq_verification_info_01.setStretch(0, 1)
        self.verticalLayout_tab_verification_info.addWidget(self.widget_eq_verification_info_01)
        self.tabWidget_eq_info.addTab(self.tab_verification_info, "")
        self.tab_storage_info = QtWidgets.QWidget()
        self.tab_storage_info.setObjectName("tab_storage_info")
        self.verticalLayout_storage_info = QtWidgets.QVBoxLayout(self.tab_storage_info)
        self.verticalLayout_storage_info.setContentsMargins(1, 2, 2, 2)
        self.verticalLayout_storage_info.setSpacing(3)
        self.verticalLayout_storage_info.setObjectName("verticalLayout_storage_info")
        self.widget_storage_info_01 = QtWidgets.QWidget(self.tab_storage_info)
        self.widget_storage_info_01.setObjectName("widget_storage_info_01")
        self.horizontalLayout_storage_info = QtWidgets.QHBoxLayout(self.widget_storage_info_01)
        self.horizontalLayout_storage_info.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_storage_info.setSpacing(3)
        self.horizontalLayout_storage_info.setObjectName("horizontalLayout_storage_info")
        self.frame_storage_info_01 = QtWidgets.QFrame(self.widget_storage_info_01)
        self.frame_storage_info_01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_storage_info_01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_storage_info_01.setObjectName("frame_storage_info_01")
        self.formLayout_storage_info_01 = QtWidgets.QFormLayout(self.frame_storage_info_01)
        self.formLayout_storage_info_01.setContentsMargins(2, 2, 2, 2)
        self.formLayout_storage_info_01.setSpacing(3)
        self.formLayout_storage_info_01.setObjectName("formLayout_storage_info_01")
        self.label_eq_person_transferred_for_storage = QtWidgets.QLabel(self.frame_storage_info_01)
        self.label_eq_person_transferred_for_storage.setObjectName("label_eq_person_transferred_for_storage")
        self.formLayout_storage_info_01.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_eq_person_transferred_for_storage)
        self.lineEdit_eq_person_transferred_for_storage_not_necessary = QtWidgets.QLineEdit(self.frame_storage_info_01)
        self.lineEdit_eq_person_transferred_for_storage_not_necessary.setObjectName("lineEdit_eq_person_transferred_for_storage_not_necessary")
        self.formLayout_storage_info_01.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_eq_person_transferred_for_storage_not_necessary)
        self.label_eq_person_transferred_from_storage = QtWidgets.QLabel(self.frame_storage_info_01)
        self.label_eq_person_transferred_from_storage.setObjectName("label_eq_person_transferred_from_storage")
        self.formLayout_storage_info_01.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_eq_person_transferred_from_storage)
        self.lineEdit_eq_person_transferred_from_storage_not_necessary = QtWidgets.QLineEdit(self.frame_storage_info_01)
        self.lineEdit_eq_person_transferred_from_storage_not_necessary.setObjectName("lineEdit_eq_person_transferred_from_storage_not_necessary")
        self.formLayout_storage_info_01.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_eq_person_transferred_from_storage_not_necessary)
        self.horizontalLayout_storage_info.addWidget(self.frame_storage_info_01)
        self.frame_storage_info_02 = QtWidgets.QFrame(self.widget_storage_info_01)
        self.frame_storage_info_02.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_storage_info_02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_storage_info_02.setObjectName("frame_storage_info_02")
        self.formLayout_storage_info_02 = QtWidgets.QFormLayout(self.frame_storage_info_02)
        self.formLayout_storage_info_02.setContentsMargins(2, 2, 2, 2)
        self.formLayout_storage_info_02.setSpacing(3)
        self.formLayout_storage_info_02.setObjectName("formLayout_storage_info_02")
        self.label_eq_transfer_to_storage_date = QtWidgets.QLabel(self.frame_storage_info_02)
        self.label_eq_transfer_to_storage_date.setObjectName("label_eq_transfer_to_storage_date")
        self.formLayout_storage_info_02.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_eq_transfer_to_storage_date)
        self.dateEdit_eq_transfer_to_storage_date = QtWidgets.QDateEdit(self.frame_storage_info_02)
        self.dateEdit_eq_transfer_to_storage_date.setMaximumSize(QtCore.QSize(110, 16777215))
        self.dateEdit_eq_transfer_to_storage_date.setObjectName("dateEdit_eq_transfer_to_storage_date")
        self.formLayout_storage_info_02.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit_eq_transfer_to_storage_date)
        self.label_eq_removal_from_storage_date = QtWidgets.QLabel(self.frame_storage_info_02)
        self.label_eq_removal_from_storage_date.setObjectName("label_eq_removal_from_storage_date")
        self.formLayout_storage_info_02.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_eq_removal_from_storage_date)
        self.dateEdit_eq_removal_from_storage_date = QtWidgets.QDateEdit(self.frame_storage_info_02)
        self.dateEdit_eq_removal_from_storage_date.setMaximumSize(QtCore.QSize(110, 16777215))
        self.dateEdit_eq_removal_from_storage_date.setObjectName("dateEdit_eq_removal_from_storage_date")
        self.formLayout_storage_info_02.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit_eq_removal_from_storage_date)
        self.horizontalLayout_storage_info.addWidget(self.frame_storage_info_02)
        self.horizontalLayout_storage_info.setStretch(0, 1)
        self.verticalLayout_storage_info.addWidget(self.widget_storage_info_01)
        self.tabWidget_eq_info.addTab(self.tab_storage_info, "")
        self.tab_repair_info = QtWidgets.QWidget()
        self.tab_repair_info.setObjectName("tab_repair_info")
        self.verticalLayout_tab_repair_info = QtWidgets.QVBoxLayout(self.tab_repair_info)
        self.verticalLayout_tab_repair_info.setContentsMargins(1, 2, 2, 2)
        self.verticalLayout_tab_repair_info.setSpacing(3)
        self.verticalLayout_tab_repair_info.setObjectName("verticalLayout_tab_repair_info")
        self.widget_repair_info_01 = QtWidgets.QWidget(self.tab_repair_info)
        self.widget_repair_info_01.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_repair_info_01.setObjectName("widget_repair_info_01")
        self.horizontalLayout_repair_info_01 = QtWidgets.QHBoxLayout(self.widget_repair_info_01)
        self.horizontalLayout_repair_info_01.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_repair_info_01.setSpacing(3)
        self.horizontalLayout_repair_info_01.setObjectName("horizontalLayout_repair_info_01")
        self.frame_repair_info_01 = QtWidgets.QFrame(self.widget_repair_info_01)
        self.frame_repair_info_01.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_repair_info_01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_repair_info_01.setObjectName("frame_repair_info_01")
        self.gridLayout_repair_info_01 = QtWidgets.QGridLayout(self.frame_repair_info_01)
        self.gridLayout_repair_info_01.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_repair_info_01.setSpacing(3)
        self.gridLayout_repair_info_01.setObjectName("gridLayout_repair_info_01")
        self.widget_repair_info_01_01 = QtWidgets.QWidget(self.frame_repair_info_01)
        self.widget_repair_info_01_01.setObjectName("widget_repair_info_01_01")
        self.horizontalLayout_repair_info_01_01 = QtWidgets.QHBoxLayout(self.widget_repair_info_01_01)
        self.horizontalLayout_repair_info_01_01.setContentsMargins(1, 2, 2, 2)
        self.horizontalLayout_repair_info_01_01.setSpacing(2)
        self.horizontalLayout_repair_info_01_01.setObjectName("horizontalLayout_repair_info_01_01")
        self.label_eq_org_repair = QtWidgets.QLabel(self.widget_repair_info_01_01)
        self.label_eq_org_repair.setMinimumSize(QtCore.QSize(140, 0))
        self.label_eq_org_repair.setObjectName("label_eq_org_repair")
        self.horizontalLayout_repair_info_01_01.addWidget(self.label_eq_org_repair)
        self.lineEdit_eq_org_repair_not_necessary = QtWidgets.QLineEdit(self.widget_repair_info_01_01)
        self.lineEdit_eq_org_repair_not_necessary.setObjectName("lineEdit_eq_org_repair_not_necessary")
        self.horizontalLayout_repair_info_01_01.addWidget(self.lineEdit_eq_org_repair_not_necessary)
        self.horizontalLayout_repair_info_01_01.setStretch(1, 1)
        self.gridLayout_repair_info_01.addWidget(self.widget_repair_info_01_01, 0, 0, 1, 1)
        self.widget_repair_info_01_02 = QtWidgets.QWidget(self.frame_repair_info_01)
        self.widget_repair_info_01_02.setObjectName("widget_repair_info_01_02")
        self.horizontalLayout_repair_info_01_02 = QtWidgets.QHBoxLayout(self.widget_repair_info_01_02)
        self.horizontalLayout_repair_info_01_02.setContentsMargins(1, 2, 2, 2)
        self.horizontalLayout_repair_info_01_02.setSpacing(2)
        self.horizontalLayout_repair_info_01_02.setObjectName("horizontalLayout_repair_info_01_02")
        self.label_eq_description_result = QtWidgets.QLabel(self.widget_repair_info_01_02)
        self.label_eq_description_result.setMinimumSize(QtCore.QSize(140, 0))
        self.label_eq_description_result.setObjectName("label_eq_description_result")
        self.horizontalLayout_repair_info_01_02.addWidget(self.label_eq_description_result)
        self.lineEdit_eq_description_result_not_necessary = QtWidgets.QLineEdit(self.widget_repair_info_01_02)
        self.lineEdit_eq_description_result_not_necessary.setObjectName("lineEdit_eq_description_result_not_necessary")
        self.horizontalLayout_repair_info_01_02.addWidget(self.lineEdit_eq_description_result_not_necessary)
        self.horizontalLayout_repair_info_01_02.setStretch(1, 1)
        self.gridLayout_repair_info_01.addWidget(self.widget_repair_info_01_02, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_repair_info_01.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout_repair_info_01.addWidget(self.frame_repair_info_01)
        self.frame_repair_info_2 = QtWidgets.QFrame(self.widget_repair_info_01)
        self.frame_repair_info_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_repair_info_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_repair_info_2.setObjectName("frame_repair_info_2")
        self.gridLayout_repair_info_2 = QtWidgets.QGridLayout(self.frame_repair_info_2)
        self.gridLayout_repair_info_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_repair_info_2.setSpacing(3)
        self.gridLayout_repair_info_2.setObjectName("gridLayout_repair_info_2")
        self.label_eq_repair_date = QtWidgets.QLabel(self.frame_repair_info_2)
        self.label_eq_repair_date.setObjectName("label_eq_repair_date")
        self.gridLayout_repair_info_2.addWidget(self.label_eq_repair_date, 0, 0, 1, 1)
        self.dateEdit_eq_repair_date = QtWidgets.QDateEdit(self.frame_repair_info_2)
        self.dateEdit_eq_repair_date.setMaximumSize(QtCore.QSize(110, 16777215))
        self.dateEdit_eq_repair_date.setObjectName("dateEdit_eq_repair_date")
        self.gridLayout_repair_info_2.addWidget(self.dateEdit_eq_repair_date, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_repair_info_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.gridLayout_repair_info_2.setColumnStretch(0, 1)
        self.horizontalLayout_repair_info_01.addWidget(self.frame_repair_info_2)
        self.horizontalLayout_repair_info_01.setStretch(0, 1)
        self.verticalLayout_tab_repair_info.addWidget(self.widget_repair_info_01)
        self.tabWidget_eq_info.addTab(self.tab_repair_info, "")
        self.verticalLayout_equipment_01.addWidget(self.tabWidget_eq_info)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_equipment_01.addItem(spacerItem4)
        self.widget_eq_info_btn = QtWidgets.QWidget(self.frame_equipment_01)
        self.widget_eq_info_btn.setMaximumSize(QtCore.QSize(16777215, 32))
        self.widget_eq_info_btn.setObjectName("widget_eq_info_btn")
        self.horizontalLayout_eq_info_btn = QtWidgets.QHBoxLayout(self.widget_eq_info_btn)
        self.horizontalLayout_eq_info_btn.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_eq_info_btn.setSpacing(2)
        self.horizontalLayout_eq_info_btn.setObjectName("horizontalLayout_eq_info_btn")
        self.frame_extended_hint = QtWidgets.QFrame(self.widget_eq_info_btn)
        self.frame_extended_hint.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extended_hint.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extended_hint.setObjectName("frame_extended_hint")
        self.horizontalLayout_extended_hint = QtWidgets.QHBoxLayout(self.frame_extended_hint)
        self.horizontalLayout_extended_hint.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_extended_hint.setSpacing(2)
        self.horizontalLayout_extended_hint.setObjectName("horizontalLayout_extended_hint")
        self.label_extended_hint = QtWidgets.QLabel(self.frame_extended_hint)
        self.label_extended_hint.setObjectName("label_extended_hint")
        self.horizontalLayout_extended_hint.addWidget(self.label_extended_hint)
        self.horizontalLayout_eq_info_btn.addWidget(self.frame_extended_hint)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_eq_info_btn.addItem(spacerItem5)
        self.pushButton_eq_info_btn_cancel = QtWidgets.QPushButton(self.widget_eq_info_btn)
        self.pushButton_eq_info_btn_cancel.setObjectName("pushButton_eq_info_btn_cancel")
        self.horizontalLayout_eq_info_btn.addWidget(self.pushButton_eq_info_btn_cancel)
        self.pushButton_eq_info_save = QtWidgets.QPushButton(self.widget_eq_info_btn)
        self.pushButton_eq_info_save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_eq_info_save.setObjectName("pushButton_eq_info_save")
        self.horizontalLayout_eq_info_btn.addWidget(self.pushButton_eq_info_save)
        self.horizontalLayout_eq_info_btn.setStretch(0, 1)
        self.verticalLayout_equipment_01.addWidget(self.widget_eq_info_btn)
        self.verticalLayout_equipment_01.setStretch(2, 1)
        self.verticalLayout.addWidget(self.frame_equipment_01)

        self.retranslateUi(Form)
        self.tabWidget_eq_info.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Frame"))
        self.groupBox_eq_info.setTitle(_translate("Form", "Сведения об испытательном оборудовании"))
        self.label_eq_info_01_equipment_name.setText(_translate("Form", "Наименование"))
        self.label_eq_type.setText(_translate("Form", "Тип"))
        self.label_eq_info_02_equipment_type.setText(_translate("Form", "Тип (марка)"))
        self.label_eq_info_03_equipment_factory_num.setText(_translate("Form", "Заводской\n"
"номер"))
        self.label_eq_info_04_manufacturer_name.setText(_translate("Form", "Завод\n"
"изготовитель"))
        self.label_eq_info_05_eq_manufacturing_date.setText(_translate("Form", "Дата изготовления"))
        self.label_eq_info_05_eq_commissioning_date.setText(_translate("Form", "Дата ввода\n"
"в эксплуатацию"))
        self.label_eq_info_06_equipment_inv_num.setText(_translate("Form", "Инвентарный\n"
"номер"))
        self.label_eq_info_07_measuring_range.setText(_translate("Form", "Диапазон\n"
"измерений"))
        self.label_eq_info_07_razdelitel.setText(_translate("Form", "-"))
        self.label_eq_units_of_measurement.setText(_translate("Form", "Ед.изм.:"))
        self.label_eq_info_08_eq_accuracy_class.setText(_translate("Form", "Класс точности\n"
"(погрешность)"))
        self.label_eq_info_09_technical_character.setText(_translate("Form", "Основные тех.\n"
"характеристики"))
        self.label_eq_info_10_other_info.setText(_translate("Form", "Иные сведения"))
        self.label_eq_passport.setText(_translate("Form", "Паспорт"))
        self.groupBox_eq_test_method.setTitle(_translate("Form", "Выбрать метод испытаний"))
        self.label_eq_verification_certificate.setText(_translate("Form", "№ свидетельства\n"
"(сертификата), аттестата:"))
        self.comboBox_eq_verification_result.setItemText(0, _translate("Form", "Пройдено"))
        self.comboBox_eq_verification_result.setItemText(1, _translate("Form", "Не пройдено"))
        self.label_eq_verification_result.setText(_translate("Form", "Результат\n"
"(пройдена/не пройдена):"))
        self.label_eq_organization_verification.setText(_translate("Form", "Организация проводившая\n"
"поверку/аттестацию:"))
        self.label_eq_verification_date.setText(_translate("Form", "Дата проведения"))
        self.label_eq_regular_verification_date.setText(_translate("Form", "Дата очередной\n"
"поверки/аттестации"))
        self.tabWidget_eq_info.setTabText(self.tabWidget_eq_info.indexOf(self.tab_verification_info), _translate("Form", "Сведения по поверке (калибровке), аттестации"))
        self.label_eq_person_transferred_for_storage.setText(_translate("Form", "Фамилия лица, переводившего СИ (ИО)\n"
"на хранение (консервацию)"))
        self.label_eq_person_transferred_from_storage.setText(_translate("Form", "Фамилия, проводившего снятие СИ (ИО)\n"
"с хранения (консервации)"))
        self.label_eq_transfer_to_storage_date.setText(_translate("Form", "Дата перевода на хранение (консервация)"))
        self.label_eq_removal_from_storage_date.setText(_translate("Form", "Дата снятия с хранения (консервации)"))
        self.tabWidget_eq_info.setTabText(self.tabWidget_eq_info.indexOf(self.tab_storage_info), _translate("Form", "Сведения о хранении (консервации)"))
        self.label_eq_org_repair.setText(_translate("Form", "Лицо/организация\n"
"проводившая ремонт"))
        self.label_eq_description_result.setText(_translate("Form", "Краткое описание\n"
"работ и результат"))
        self.label_eq_repair_date.setText(_translate("Form", "Дата проведения"))
        self.tabWidget_eq_info.setTabText(self.tabWidget_eq_info.indexOf(self.tab_repair_info), _translate("Form", "Сведения о ремонте"))
        self.label_extended_hint.setText(_translate("Form", "Расширенная подсказка"))
        self.pushButton_eq_info_btn_cancel.setText(_translate("Form", "Отмена"))
        self.pushButton_eq_info_save.setText(_translate("Form", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QFrame()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
