# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 616)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_content = QtWidgets.QFrame(self.frame_center)
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_content = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_content.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_content.setSpacing(1)
        self.verticalLayout_content.setObjectName("verticalLayout_content")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_equipment = QtWidgets.QWidget()
        self.page_equipment.setObjectName("page_equipment")
        self.gridLayout_equipment = QtWidgets.QGridLayout(self.page_equipment)
        self.gridLayout_equipment.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_equipment.setSpacing(1)
        self.gridLayout_equipment.setObjectName("gridLayout_equipment")
        self.splitter_equipment_info = QtWidgets.QSplitter(self.page_equipment)
        self.splitter_equipment_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_equipment_info.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_equipment_info.setObjectName("splitter_equipment_info")
        self.widget_equipment_info_right = QtWidgets.QWidget(self.splitter_equipment_info)
        self.widget_equipment_info_right.setObjectName("widget_equipment_info_right")
        self.verticalLayout_equipment_info_right_2 = QtWidgets.QVBoxLayout(self.widget_equipment_info_right)
        self.verticalLayout_equipment_info_right_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_equipment_info_right_2.setSpacing(2)
        self.verticalLayout_equipment_info_right_2.setObjectName("verticalLayout_equipment_info_right_2")
        self.listWidget_equipment_list = QtWidgets.QListWidget(self.widget_equipment_info_right)
        self.listWidget_equipment_list.setObjectName("listWidget_equipment_list")
        self.verticalLayout_equipment_info_right_2.addWidget(self.listWidget_equipment_list)
        self.verticalLayout_equipment_info_right_2.setStretch(0, 1)
        self.widget_equipment_info_left = QtWidgets.QWidget(self.splitter_equipment_info)
        self.widget_equipment_info_left.setObjectName("widget_equipment_info_left")
        self.verticalLayout_equipment_info_left_2 = QtWidgets.QVBoxLayout(self.widget_equipment_info_left)
        self.verticalLayout_equipment_info_left_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_equipment_info_left_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_equipment_info_left_2.setSpacing(2)
        self.verticalLayout_equipment_info_left_2.setObjectName("verticalLayout_equipment_info_left_2")
        self.tabWidget_equipment_info_table = QtWidgets.QTabWidget(self.widget_equipment_info_left)
        self.tabWidget_equipment_info_table.setObjectName("tabWidget_equipment_info_table")
        self.tab_general_information = QtWidgets.QWidget()
        self.tab_general_information.setObjectName("tab_general_information")
        self.verticalLayout_general_information = QtWidgets.QVBoxLayout(self.tab_general_information)
        self.verticalLayout_general_information.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_general_information.setSpacing(2)
        self.verticalLayout_general_information.setObjectName("verticalLayout_general_information")
        self.tableView_general_information = QtWidgets.QTableView(self.tab_general_information)
        self.tableView_general_information.setObjectName("tableView_general_information")
        self.verticalLayout_general_information.addWidget(self.tableView_general_information)
        self.verticalLayout_general_information.setStretch(0, 1)
        self.tabWidget_equipment_info_table.addTab(self.tab_general_information, "")
        self.tab_verification_info = QtWidgets.QWidget()
        self.tab_verification_info.setObjectName("tab_verification_info")
        self.verticalLayout_verification_info = QtWidgets.QVBoxLayout(self.tab_verification_info)
        self.verticalLayout_verification_info.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_verification_info.setSpacing(2)
        self.verticalLayout_verification_info.setObjectName("verticalLayout_verification_info")
        self.tableView_eq_verification_info = QtWidgets.QTableView(self.tab_verification_info)
        self.tableView_eq_verification_info.setObjectName("tableView_eq_verification_info")
        self.verticalLayout_verification_info.addWidget(self.tableView_eq_verification_info)
        self.tabWidget_equipment_info_table.addTab(self.tab_verification_info, "")
        self.tab_storage_info = QtWidgets.QWidget()
        self.tab_storage_info.setObjectName("tab_storage_info")
        self.verticalLayout_storage_info = QtWidgets.QVBoxLayout(self.tab_storage_info)
        self.verticalLayout_storage_info.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_storage_info.setSpacing(2)
        self.verticalLayout_storage_info.setObjectName("verticalLayout_storage_info")
        self.tableView_storage_info = QtWidgets.QTableView(self.tab_storage_info)
        self.tableView_storage_info.setObjectName("tableView_storage_info")
        self.verticalLayout_storage_info.addWidget(self.tableView_storage_info)
        self.tabWidget_equipment_info_table.addTab(self.tab_storage_info, "")
        self.tab_repair_info = QtWidgets.QWidget()
        self.tab_repair_info.setObjectName("tab_repair_info")
        self.verticalLayout_repair_info = QtWidgets.QVBoxLayout(self.tab_repair_info)
        self.verticalLayout_repair_info.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_repair_info.setSpacing(2)
        self.verticalLayout_repair_info.setObjectName("verticalLayout_repair_info")
        self.tableVieweq_repair_info = QtWidgets.QTableView(self.tab_repair_info)
        self.tableVieweq_repair_info.setObjectName("tableVieweq_repair_info")
        self.verticalLayout_repair_info.addWidget(self.tableVieweq_repair_info)
        self.tabWidget_equipment_info_table.addTab(self.tab_repair_info, "")
        self.verticalLayout_equipment_info_left_2.addWidget(self.tabWidget_equipment_info_table)
        self.gridLayout_equipment.addWidget(self.splitter_equipment_info, 1, 1, 1, 1)
        self.frame_equipment_buttons = QtWidgets.QFrame(self.page_equipment)
        self.frame_equipment_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_equipment_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_equipment_buttons.setObjectName("frame_equipment_buttons")
        self.verticalLayout_equipment_buttons = QtWidgets.QVBoxLayout(self.frame_equipment_buttons)
        self.verticalLayout_equipment_buttons.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_equipment_buttons.setSpacing(1)
        self.verticalLayout_equipment_buttons.setObjectName("verticalLayout_equipment_buttons")
        self.pushButton_eq_add = QtWidgets.QPushButton(self.frame_equipment_buttons)
        self.pushButton_eq_add.setText("")
        self.pushButton_eq_add.setObjectName("pushButton_eq_add")
        self.verticalLayout_equipment_buttons.addWidget(self.pushButton_eq_add)
        self.pushButton_eq_delete = QtWidgets.QPushButton(self.frame_equipment_buttons)
        self.pushButton_eq_delete.setText("")
        self.pushButton_eq_delete.setObjectName("pushButton_eq_delete")
        self.verticalLayout_equipment_buttons.addWidget(self.pushButton_eq_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_equipment_buttons.addItem(spacerItem)
        self.verticalLayout_equipment_buttons.setStretch(2, 1)
        self.gridLayout_equipment.addWidget(self.frame_equipment_buttons, 1, 0, 1, 1)
        self.frame_select_eq_type = QtWidgets.QFrame(self.page_equipment)
        self.frame_select_eq_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_select_eq_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_select_eq_type.setObjectName("frame_select_eq_type")
        self.horizontalLayout_select_eq_type_2 = QtWidgets.QHBoxLayout(self.frame_select_eq_type)
        self.horizontalLayout_select_eq_type_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_select_eq_type_2.setSpacing(2)
        self.horizontalLayout_select_eq_type_2.setObjectName("horizontalLayout_select_eq_type_2")
        self.lineEdit_equipment_search = QtWidgets.QLineEdit(self.frame_select_eq_type)
        self.lineEdit_equipment_search.setObjectName("lineEdit_equipment_search")
        self.horizontalLayout_select_eq_type_2.addWidget(self.lineEdit_equipment_search)
        self.comboBox_search_eq_type = QtWidgets.QComboBox(self.frame_select_eq_type)
        self.comboBox_search_eq_type.setObjectName("comboBox_search_eq_type")
        self.horizontalLayout_select_eq_type_2.addWidget(self.comboBox_search_eq_type)
        self.gridLayout_equipment.addWidget(self.frame_select_eq_type, 0, 0, 1, 2)
        self.gridLayout_equipment.setColumnStretch(1, 1)
        self.gridLayout_equipment.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page_equipment)
        self.verticalLayout_content.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_content)
        self.verticalLayout_5.addWidget(self.frame_center)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_equipment_info_table.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget_equipment_info_table.setTabText(self.tabWidget_equipment_info_table.indexOf(self.tab_general_information), _translate("MainWindow", "Общая информация"))
        self.tabWidget_equipment_info_table.setTabText(self.tabWidget_equipment_info_table.indexOf(self.tab_verification_info), _translate("MainWindow", "Сведения по поверке (калибровке), аттестации"))
        self.tabWidget_equipment_info_table.setTabText(self.tabWidget_equipment_info_table.indexOf(self.tab_storage_info), _translate("MainWindow", "Сведения о хранении (консервации)"))
        self.tabWidget_equipment_info_table.setTabText(self.tabWidget_equipment_info_table.indexOf(self.tab_repair_info), _translate("MainWindow", "Сведения о ремонте"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
